### PR TITLE
Update your Readme.md

### PR DESCRIPTION
**Pull request by TDRMinecraft**
I add a much better Description for Knet!

- better headers
- more information
- better showcase

### CODE REVIEW

**Review by DSeeLPYT — CHANGES_REQUESTED** [review]
Fix typo in line 17

**Review by TDRMinecraft — COMMENTED** [review]
This gives you a better base for working on your Readme.md

**Comment by TDRMinecraft** [comment]
> Fix typo in line 17

Do it your self!

**Comment by DSeeLPYT** [comment]
I write a own Readme later. But thanks

**Pull request closed without merging**
